// Code generated by generate-database from the incus project - DO NOT EDIT.

package cluster

import (
	"errors"
	"fmt"
)

type errType int

const (
	errTypeNotFound errType = iota
	errTypeConflict
)

var errMap = map[errType]func(err error, entity string) error{
	errTypeNotFound: func(_ error, _ string) error { return errors.New("Not found") },
	errTypeConflict: func(_ error, _ string) error { return errors.New("Conflict") },
}

func mapErr(et errType, err error, entity string) error {
	errFunc, ok := errMap[et]
	if !ok {
		return fmt.Errorf("err type %d is not defined", et)
	}

	return errFunc(err, entity)
}
