// Code generated by generate-database from the incus project - DO NOT EDIT.

package cluster

import (
	"errors"
)

var (
	ErrNotFound = errors.New("Not found")
	ErrConflict = errors.New("Conflict")
)

var mapErr = defaultMapErr

func defaultMapErr(err error, entity string) error {
	return err
}
